garritfra/darktheme.club

- _data/sites.yml
This PR is:
```
- domain: duckduckgo.com
url: https://duckduckgo.com/
method: unknown
```
> Add duckduckgo.com

- _data/sites.yml
This PR is:
```
- domain: github.com
url: https://github.com/
```
> Add github.com

- _data/sites.yml
This PR is:
```
- domain: jlelse.blog
url: https://jlelse.blog/
```
> Add jlelse.blog

- _data/sites.yml
This PR is:
```
- domain: phishwarn.codeberg.page
url: https://phishwarn.codeberg.page/
```
> Add phishwarn.codeberg.page

- _data/sites.yml
This PR is:
```
- domain: bfoliver.com
url: https://www.bfoliver.com
```
> Add bfoliver.com

- _data/sites.yml
> add revuo-xmr

- _data/sites.yml
This PR is:
```
- domain: taylantatli.com
url: https://taylantatli.com/
last_checked: 2022-07-17
```
> Add taylantatli.com

- _includes/sites.html
- assets/css/style.css
> Show dark-theme method in listing

- _data/sites.yml
This PR is:
```
- domain: inherently.xyz
url: https://inherently.xyz/
last_checked: 2022-07-17
```
> Add inherently.xyz

- _data/sites.yml
This PR is:
```
- domain: feedmail.org
url: https://feedmail.org
```
> Add FeedMail.

- _data/sites.yml
This PR is:
```
- domain: lkhrs.com
url: https://www.lkhrs.com/
last_checked: 2022-07-17
```
> Add lkhrs.com

- _data/sites.yml
This PR is:
```
- domain: seirdy.one
url: https://seirdy.one/
last_checked: 2022-07-18
```
> Add seirdy.one

- _data/sites.yml
This PR is:
```
- domain: bubble.email
url: https://bubble.email
last_checked: 2022-07-17
```
> add bubble.email

- _data/sites.yml
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Add bernsteinbear.com

- _data/sites.yml
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Add pragmaticpineapple.com

- _data/sites.yml
added https://aitrack.work/
This PR is:
```- domain: aitrack.work
url: https://aitrack.work/
last_checked: 2022-07-19
```
> add: aitrack.work

- _data/sites.yml
Thanks for merging my PR, I'm adding another FOSS app I made that should satisfy the "darkonly" criteria.
This PR is:
```
- domain: watch3r.app
url: https://watch3r.app/
last_checked: 2022-07-20
```
> add: watch3r.app

- _data/sites.yml
Uses mediaquery by default but also allows override with javascript
This PR is:
```
- domain: forgefed.org
url: https://forgefed.org
last_checked: 2022-07-21
```
> Add forgefed.org

- _data/sites.yml
This PR is:
```
- domain: tauri.app
url: https://tauri.app/
last_checked: 2022-07-21
```
> Add tauri.app

- .github/PULL_REQUEST_TEMPLATE.yml
Fixes #27
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Remove minimal content guideline from PR template

- _data/sites.yml
This PR is:
```
- domain: emanuelpina.pt
url: https://emanuelpina.pt/
last_checked: 2022-07-24
```
> Add emanuelpina.pt

- _data/sites.yml
This PR is:
```
- domain: radiocanadamini.ca
url: https://radiocanadamini.ca/
last_checked: 2022-10-03
```
> Add radiocanadamini.ca

- _data/sites.yml
This PR is:
```
- domain: nih.ar
url: https://nih.ar
last_checked: 2022-10-23
```
> Add nih.ar

- _data/sites.yml
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Update sites.yml - + home.omg.lol

- _data/sites.yml
This PR is:
```
- domain: rohandebsarkar.github.io
url: https://rohandebsarkar.github.io/
last_checked: 2022-10-30
```
> Add `rohandebsarkar.github.io`

- _data/sites.yml
This PR is:
```
- domain: 5am.is
url: https://5am.is/
last_checked: 2022-11-26
```
> Add 5am.is

- _data/sites.yml
This PR is:
```
- domain: cleberg.net
url: https://cleberg.net/
last_checked: 2022-12-17
```
> add cleberg.net

- _data/sites.yml
Website (if applicable): https://foreverliketh.is/
This PR is:
```
- domain:
url:
method:
last_checked:
```
> add website

- _data/sites.yml
Website (if applicable): https://www.adamsdesk.com/
This PR is:
```
- domain: adamsdesk.com
url: https://www.adamsdesk.com/
last_checked: 2022-01-02
```
> Add adamsdesk.com

- _includes/faq-02.html
- _includes/faq-03.html
- _includes/faq-04.html
- _includes/faq-05.html
- _layouts/default.html
- faq.md
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Add attribution banner

- _data/sites.yml
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Added my website

- _data/sites.yml
Website (if applicable): https://traeblain.com
This PR is:
```
- domain: traeblain.com
url: https://traeblain.com
last_checked: 2023-01-05
```
> Added traeblain.com to darkmode.club

- _data/sites.yml
- index.md
also added a sort to the domains, so jekyll can render the alpha order as well and the action script can confirm the order.
Website (if applicable): https://claytonerrington.com
This PR is:
```
- domain: claytonerrington.com
url: https://claytonerrington.com/
last_checked: 2023-01-07
```
> added claytonerrington.com to darktheme.club

- _data/sites.yml
Website (if applicable): https://chino.is-a.dev/
This PR is:
```
- domain: chino.is-a.dev
url: https://chino.is-a.dev/
last_checked: 2023-02-01
```
> Add chino.is-a.dev

- _data/sites.yml
Website (if applicable): https://ff99cc.art
This PR is:
```
- domain: ff99cc.art
url: https://ff99cc.art/
last_checked: 2023-02-02
```
> Add ff99cc.art

- _data/sites.yml
Website (if applicable): https://cleberg.net
This PR is:
```
- domain: cleberg.net
url: https://cleberg.net/
last_checked: 2023-02-03
```
> update method for cleberg.net

- _data/sites.yml
Website (if applicable): https://til.pm
This PR is:
> add til.pm

- _data/sites.yml
Website (if applicable): https://www.uncenter.org/
This PR is:
```
- domain: uncenter.org
url: https://www.uncenter.org/
last_checked: 2023-02-20
```
> Add uncenter.org

- _data/sites.yml
Website (if applicable): https://madelinepritchard.net <-- TODO: CHANGE ME
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Add madelinepritchard.net

- _data/sites.yml
Website (if applicable): https://jacksonchen666.com
This PR is:
> add jacksonchen666.com

- _data/sites.yml
Website (if applicable): https://sheepdev.xyz/
This PR is:
```
- domain: sheepdev.xyz
url: https://sheepdev.xyz/
last_checked: 2023-03-01
```
> add sheepdev.xyz

- _data/sites.yml
Website (if applicable): https://blog.madelinepritchard.net <-- TODO: CHANGE ME
This PR is:
```
- domain: blog.madelinepritchard.net
url: https://blog.madelinepritchard.net/
last_checked: 2023-03-20
```
> Add blog.madelinepritchard.net

- _data/sites.yml
Website (if applicable): <https://vanzasetia.site/>
This PR is:
```
- domain: vanzasetia.site
url: https://vanzasetia.site/
last_checked: 2023-03-26
```
> Add vanzasetia.site

- _data/sites.yml
Website (if applicable): https://libre.town/
This PR is:
- [ X ] Adding a new domain
- [ X ] The domain is in the correct alphabetical order
- [ X ] The following information is filled identical to the data file
- [ X ] Check to confirm
```
- domain: libre.town
url: https://libre.town/
last_checked: 2023-03-27
```
> Add Libre.Town to the site list

- _data/sites.yml
Website (if applicable): https://cleberg.net
This PR is:
```
- domain:
url:
method:
last_checked:
```
> remove cleberg.net

- _data/sites.yml
Website (if applicable): https://ted.magaoay.org
This PR is:
```
- domain: ted.magaoay.org
url: https://ted.magaoay.org/
last_checked: 2023-03-28
```
> Add ted.magaoay.org

- _data/sites.yml
Website (if applicable): https://thelazysre.com
This PR is:
```
- domain: thelazysre.com  
url: https://thelazysre.com/
last_checked: 2023-04-02
```
> Add thelazysre.com to sites.yml

- _data/sites.yml
Website (if applicable): https://cosmicqbit.dev 
This PR is:
```
- domain: cosmicqbit.dev
url: https://cosmicqbit.dev
last_checked: 2023-04-12
```
> Add cosmicqbit.dev

- _data/sites.yml
Website: https://kathut.de/
This PR is:
```
- domain: kathut.de
url: http://kathut.de/
last_checked: 2023-04-16
```
> Add kathut.de

- _data/sites.yml
Website: https://darekkay.com
This PR is:
```
- domain: darekkay.com
url: https://darekkay.com/
last_checked: 2023-04-17
```
> Add darekkay.com website

- _data/sites.yml
Websites: https://minutestomidnight.co.uk and https://simonesilvestroni.com
This PR is:
```
- domain: minutestomidnight.co.uk
url: https://minutestomidnight.co.uk/
last_checked: 2023-04-17
```
```
- domain: simonesilvestroni.com
url: https://simonesilvestroni.com/
last_checked: 2023-04-17
```
> Added two sites

- _data/sites.yml
Website (if applicable): https://basementcommunity.com
This PR is:
> Add basementcommunity.com

- _data/sites.yml
Website (if applicable): https://colincogle.name <-- TODO: CHANGE ME
This PR is:
```yaml
- domain: colincogle.name
url: https://colincogle.name/
last_checked: 2023-05-19
```
> Add colincogle.name to sites.yml

- _data/sites.yml
Website (if applicable): https://kaifa.ch
This PR is:
```
- domain: kaifa.ch
url: https://kaifa.ch/
last_checked: 2023-05-23
```
> Add kaifa.ch

- _data/sites.yml
Website (if applicable): https://cleberg.net
This PR is:
```
- domain: cleberg.net
url: https://cleberg.net/
last_checked: 2023-05-22
```
> re-add cleberg.net now that the site is functional again

- _data/sites.yml
Website (if applicable): https://alessandrocuzzocrea.com
This PR is:
```
- domain: alessandrocuzzocrea.com
url: https://alessandrocuzzocrea.com
last_checked: 2023-05-26
```
> Add alessandrocuzzocrea.com

- _data/sites.yml
Website: https://sebastinux.com
This PR is:
```
- domain: sebastinux.com
url: https://sebastinux.com/
last_checked: 2023-05-31
```
> Add sebastinux.com

- _data/sites.yml
Website (if applicable): ineedmore.coffee
This PR is:
```
- domain: ineedmore.coffee
url: https://ineedmore.coffee
last_checked: 2023-06-23
```
> Added ineedmore.coffee to list of sites

- _data/sites.yml
Website (if applicable): https://ineedmore.coffee
This PR is:
```
- domain: ineedmore.coffee
url: https://ineedmore.coffee
last_checked: 2023-06-23
```
> Fixing my site's entry in sites.yml

- _data/sites.yml
Website (if applicable): https://hen.ee
This PR is:
Checked:
> Added hen.ee to sites.yml

- _data/sites.yml
Website (if applicable): https://kirillunlimited.com
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Add kirillunlimited.com

- Gemfile.lock
- _data/navigation.yml
- _data/sites.yml
- _plugins/rss_feed.rb
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Add rss feed plugin

- _data/sites.yml
Website (if applicable): https://kimchiii.space
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Add `kimchiii.space`

- _data/sites.yml
Websites : https://scientiac.space and https://map.scientiac.space
This PR is:
```
- domain: map.scientiac.space
url: https://map.scientiac.space/
last_checked: 2023-09-11
```
and
```
- domain: scientiac.space
url: https://scientiac.space/
last_checked: 2023-09-11
```
> Added scientiac.space and map.scientiac.space to the list.

- _data/sites.yml
Website (if applicable): https://konstantintutsch.de
This PR is:
```
- domain: konstantintutsch.de
url: https://konstantintutsch.de/
last_checked: 2023-10-07
```
> Add site konstantintutsch.de

- _data/sites.yml
Website (if applicable): https://mnsr.win
This PR is:
```
- domain: mnsr.win
url: https://mnsr.win/
last_checked: 2023-10-112
```
> Added mnsr.win to sites.yml

- _data/sites.yml
Website (if applicable): https://dillonbaird.io
This PR is:
```
- domain: dillonbaird.io
url: https://dillonbaird.io/
last_checked: 2023-10-12
```
> Added dillonbaird.io to sites.yaml

- _data/sites.yml
Website: https://blog.vinfall.com
This PR is:
```
- domain: blog.vinfall.com
url: https://blog.vinfall.com/
last_checked: 2023-10-14
```
> Add `blog.vinfall.com`

- _data/sites.yml
Website (if applicable): https://beuke.org
This PR is:
```
- domain: beuke.org
url: http://beuke.org/
last_checked: 2023-10-17
```
> Update sites.yml add beuke.org

- .github/PULL_REQUEST_TEMPLATE.yml
- .github/workflows/ci.yml
- README.md
- _data/sites.yml
- scripts/site_stats.sh
Ref: #51
See also: https://github.com/kevquirk/512kb.club/pull/1339
> Fix formatting in PRs

- _data/sites.yml
Website (if applicable): https://konstantintutsch.de
This PR is:
```
- domain: konstantintutsch.com
url: https://konstantintutsch.com/
last_checked: 2023-11-11
```
> Modify domain konstantintutsch.de to konstantintutsch.com

- _data/sites.yml
Website: https://storydragon.nl
This PR is:
```
- domain: storydragon.nl
url: https://storydragon.nl
last_checked: 2023-11-13
```
> Add storydragon.nl

- _data/sites.yml
This PR is:
```
- domain: hans.gerwitz.com
url: https://hans.gerwitz.com/
last_checked: 2023-11-20
```
> Adding hans.gerwitz.com

- _data/sites.yml
Website: https://ksbrooksjr.com/
This PR is:
```
- domain: ksbrooksjr.com
url: https://ksbrooksjr.com/
last_checked: 2023-11-24
```
> add site ksbrooksjr.com

- _data/sites.yml
Website (if applicable): https://hacdias.com/
This PR is:
```
- domain: hacdias.com
url: https://hacdias.com
last_checked: 2023-11-25
```
---
I do wish it was CSS only. I think browser vendors should allow overriding the OS "prefers-color-schema" per website. I do default to the user's, but let them choose. It's a bit sad that that customization bit requires js.
> Add hacdias.com

- _data/sites.yml
Website (if applicable): https://hex.moonwith.com
This PR is:
```
- domain: hex.moonwith.com
url: http://hex.moonwith.com/
last_checked: 2023-11-27
```
> Add hex.moonwith.com

- _data/sites.yml
Website (if applicable): https://eternodevir.com/
This PR is:
```
- domain: eternodevir.com
url: https://eternodevir.com/
last_checked: 2023-12-20
```
> Add eternodevir.com

- _data/sites.yml
Website (if applicable): https://mini.moonlab.top
This PR is:
```
- domain: mini.moonlab.top
url: https://mini.moonlab.top/
last_checked: 2023-12-26
```
> Add mini.moonlab.top

- _data/sites.yml
Website (if applicable): https://adast.dk
This PR is:
- [ x] Adding a new domain
- [ x] The following information is filled identical to the data file
- [ x] Check to confirm
```
- domain: adast.dk
url: https://adast.dk/ 
method: mediaquery 
last_checked: 2024-01-11
```
> Add adast.dk

- _data/sites.yml
Website (if applicable): https://petercammeraat.net <-- TODO: CHANGE ME
This PR is:
```
- domain: petercammeraat.net
url: https://petercammeraat.net/
last_checked: 2024-01-16
```
> changed 5am.is to petercammeraat.net

- _data/sites.yml
Website (if applicable): https://denisdefreyne.com/
This PR is:
```
- domain: denisdefreyne.com
url: https://denisdefreyne.com/
last_checked: 2024-01-20
```
> Add denisdefreyne.com to sites.yml

- _data/sites.yml
Website (if applicable): https://bukmark.club <-- TODO: CHANGE ME
This PR is:
```
- domain: bukmark.club
url: https://bukmark.club/
last_checked: 2024-02-19
```
> add: bukmark.club

- _data/sites.yml
This PR is:
```
- domain:
url:
method:
last_checked:
```
> added my blog

- _data/sites.yml
This PR is:
---
---
```
- domain: zwbetz.com
url: https://zwbetz.com/
last_checked: 2024-02-27
```
> add zwbetz.com

- _data/sites.yml
Website (if applicable): https://timikels.com
This PR is:
```
- domain: timikels.com
url: https://timikels.com/blog/
last_checked: 2024-03-08
```
> Update sites.yml - added timikels.com/blog/ - THANK YOU

- _data/sites.yml
Website (if applicable): https://kidl.at <-- TODO: CHANGE ME
This PR is:
```
- domain: kidl.at
url: https://kidl.at/
last_checked: 2024-03-08
```
> Add kidl.at to sites.yml

- _data/sites.yml
Website (if applicable): https://r74n.com
This PR is:
```
- domain: r74n.com
url: https://r74n.com/
last_checked: 2024-03-20
```
> Added R74n to sites.yml

- _data/sites.yml
Website (if applicable): https://frills.dev
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Add frills.dev

- _data/sites.yml
Website (if applicable): https://koehr.ing and https://250kb.club
This PR is:
```
- domain: 250kb.club
url: https://250kb.club/
last_checked: 2024-03-30
- domain: koehr.ing
url: https://koehr.ing/
last_checked: 2024-03-30
```
> Adds koehr.ing and 250kb.club

- _data/sites.yml
Website (if applicable): https://vanzasetia.site <-- TODO: CHANGE ME
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Remove vanzasetia.site

- _data/sites.yml
Website (if applicable): https://gagor.pro
This PR is:
```
- domain: gagor.pro
url: https://gagor.pro/
last_checked: 2024-04-16
```
> Add gagor.pro

- _data/sites.yml
Website (if applicable): https://visil.gw.lt/
This PR is:
```
- domain: visil.gw.lt
url: https://visil.gw.lt/
last_checked: 2024-04-28
```
> Added a site to sites.yml

- _data/sites.yml
Website (if applicable): https://thatmlopsguy.github.io/
This PR is:
```
- domain: thatmlopsguy.github.io
url: https://thatmlopsguy.github.io/
last_checked: 2024-05-15
```
> Add That MLOps Guy

- _data/sites.yml
Website (if applicable): https://ferrad.as
This PR is:
```
- domain: ferrad.as
url: https://ferrad.as/
last_checked: 2023-06-04
```
> Add ferrad.as to sites.yml

- _data/sites.yml
Website (if applicable): https://vale.rocks
This PR is:
```
- domain: vale.rocks
url: https://vale.rocks/
last_checked: 2024-06-24
```
> Add vale.rocks to list

- _data/sites.yml
This PR is:
```
- domain: crism.ro
url: https://crism.ro/
last_checked: 2024-06-24
```
> Add crism.ro to sites.yml

- _data/sites.yml
Website (if applicable): https://eklausmeier.goip.de
This PR is:
```
- domain: eklausmeier.goip.de
url: https://eklausmeier.goip.de/
last_checked: 2024-07-13
```
> Add eklausmeier.goip.de: should now honor smartphone system theme

- _data/sites.yml
Websites:
- https://helenchong.dev/
- https://leilukin.com/
This PR is:
```
- domain: helenchong.dev
url: https://helenchong.dev/
last_checked: 2024-07-13
```
```
- domain: leilukin.com
url: https://leilukin.com/
last_checked: 2024-07-13
```
> Add helenchong.dev and leilukin.com

- _data/sites.yml
This PR is:
```
- domain: nali.org
url: https://nali.org/
last_checked: 2024-08-22
```
> Add nali.org

- _data/sites.yml
Website (if applicable): https://asnine.me
This PR is:
```
- domain: asnine.me
url: https://asnine.me/
last_checked: 2024-08-23
```
> Add asnine.me to sites.yml

- _data/sites.yml
Added rishikeshs.com
This PR is:
```
- domain: rishikeshs.com
url: https://rishikeshs.com/
last_checked: 2024-09-27
```
> Added rishikeshs.com

- _data/sites.yml
Added per instructions
Website (if applicable): https://brentter.com/
This PR is:
```
- domain: brentter.com
url: https://brentter.com/
last_checked: 2024-10-19
```
> Added brentter.com to sites.yml

- _data/sites.yml
Website (if applicable): https://home.hedy.dev/
This PR is:
- Adding a new domain
```
- domain: home.hedy.dev
url: https://home.hedy.dev/
last_checked: 2024-10-30
```
> Add home.hedy.dev

- _data/sites.yml
Website (if applicable): https://nelson.cloud
This PR is:
```
- domain:
url:
method:
last_checked:
```
> Add nelson.cloud

- _data/sites.yml
This PR is:
I noticed several sites that were inactive. This PR removes those.
> Remove Inactive Sites

- _data/sites.yml
Website (if applicable): https://hstsethi.vercel.app/
This PR is:
```
- domain: hstsethi.vercel.app
url: https://hstsethi.vercel.app/
last_checked: 2024-11-14
```
> Add hstsethi.vercel.app

- _data/sites.yml
Website (if applicable): https://blog.leenucks.xyz
This PR is:
```
- domain: blog.leenucks.xyz
url: https://blog.leenucks.xyz/ (Make sure you keep the trailing slash)
last_checked: 2024-11-14
```
> sites.yml: add blog.leenucks.xyz

- _data/sites.yml
Website (if applicable): https://vanzasetia.xyz/
This PR is:
```
- domain: vanzasetia.xyz
url: https://vanzasetia.xyz/
last_checked: 2024-12-25
```
> Add vanzasetia.xyz

- _data/sites.yml
Website (if applicable): https://pixelflips.com
This PR is:
```
- domain: pixelflips.com
url: https://pixelflips.com/
last_checked: 2025-02-15
```
> feat: add pixelflips.com

- _data/sites.yml
Website (if applicable): https://lai.nz
This PR is:
```
- domain: lai.nz
url: https://lai.nz
method: colorscheme
last_checked: 2025-02-16
```
> Add lai.nz

- _data/sites.yml
My personal website with a darkonly theme.
Thanks for making this list! Found a bunch of great sites through it. 
Website (if applicable): https://www.leouieda.com
This PR is:
```
- domain: leouieda.com
url: https://www.leouieda.com/
last_checked: 2025-02-28
```
> Add leouieda.com

- _data/sites.yml
Website (if applicable): https://w3teal.is-a.dev/ <-- TODO: CHANGE ME
This PR is:
```
- domain: w3teal.is-a.dev
url: https://w3teal.is-a.dev/
last_checked: 2025-03-07
```
> Add w3teal.is-a.dev

- _data/sites.yml
Website (if applicable): https://jamesg.blog
This PR is:
> Add jamesg.blog

- _data/sites.yml
Website (if applicable): https://shockbs.pro/
This PR is:
```
- domain: shockbs.pro
url:
https://shockbs.pro/
method:
javascript
last_checked:
2025-03-29
```
> Add ShockBS.pro

- _data/sites.yml
This PR is:
```
- domain: cleberg.net
url: https://cleberg.net/
last_checked: 2025-04-02
```
> revert cmc.pub to cleberg.net

- _data/sites.yml
Website (if applicable): https://tombrandis.uk
This PR is:
```
- domain: tombrandis.uk
url: http://tombrandis.uk/
last_checked: 2025-04-13
```
> Add Tom Brandis site

- _data/sites.yml
Website (if applicable): https://orangc.net
This PR is:
```
- domain: orangc.net
url: https://orangc.net/
method: colorscheme
last_checked: 2025.04.20
```
> feat: add orangc.net

- _data/sites.yml
Website (if applicable): https://dospuntostr.es
This PR is:
```
- domain: dospuntostr.es
url: http://dospuntostr.es/en/
last_checked: 2025-05-05
```
> Add dospuntostr.es

- _data/sites.yml
Website (if applicable): https://joshua.seigler.net/ <-- TODO: CHANGE ME
This PR is:
```
- domain: joshua.seigler.net
url: https://joshua.seigler.net/
last_checked: 2025-06-22
```
> Add joshua.seigler.net

- _data/sites.yml
Website (if applicable): 
https://douxx.blog/
https://douxx.tech/
https://dpip.lol/
https://getan.email/
https://noskid.today/
https://theserver.life/
https://urltoapp.xyz/
https://writestorm.art/
This PR is:
```
- domain: douxx.blog
url: https://douxx.blog/
last_checked: 2025-06-24
- domain: douxx.tech
url: https://douxx.tech/
last_checked: 2025-06-24
- domain: dpip.lol
url: https://dpip.lol/
last_checked: 2025-06-24
- domain: getan.email
url: https://getan.email/
last_checked: 2025-06-24
- domain: noskid.today
url: …
```
> added some urls

- _data/sites.yml
Website (if applicable): https://alexzeecomedy.com <-- TODO: CHANGE ME
This PR is:
```
- domain: alexzeecomedy.com
url: https://alexzeecomedy.com/
last_checked: 2025-07-16
```
> Changed alexzeecomedy.com dark mode method

- _data/sites.yml
Website (if applicable): https://dpip.lol -- rewrited it, light mode only
This PR is:
```
- domain: dpip.lol
url: http://dpip.lol
last_checked: 17-07-2025
```
> Removed DPIP.lol

- _data/sites.yml
Website (if applicable): https://yellowduckyapps.com
This PR is:
```
- domain: yellowduckyapps.com
url: https://yellowduckyapps.com/
last_checked: 2025-07-31
```
> added yellowduckyapps.com

- _data/sites.yml
Website (if applicable): joelchrono.xyz <-- TODO: CHANGE ME
This PR is:
```
- domain: joelchrono.xyz
url: https://joelchrono.xyz
last_checked: 2025-08-07
```
> Update url for joelchrono.xyz

- _data/sites.yml
Website (if applicable): https://peterspath.net
This PR is:
```
- domain: peterspath.net
url: https://peterspath.net/
last_checked: 2025-08-07
```
> added peterspath.net

- _data/sites.yml
Website (if applicable): https://jann.stute.dev
This PR is:
```
- domain: jann.stute.dev
url: https://jann.stute.dev/
last_checked: 2025-09-05
```
> Added jann.stute.dev

- _data/sites.yml
Website (if applicable): https://perrotta.dev/
This PR is:
```
- domain: perrotta.dev
url: https://perrotta.dev/
last_checked: 2025-09-18
```
> add perrotta.dev
